"""
CooperCorp PRJ-002 — Signal Logger
Logs every signal generated by the scan pipeline — including those NOT acted on.
Enables retroactive accuracy verification and continuous learning from all decisions.
"""
import json
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).parent.parent.parent
SIGNALS_FILE = REPO_ROOT / "logs" / "signals.jsonl"


class SignalLogger:
    """
    Logs every signal generated by the scan pipeline.
    Tracks: what signal was given, at what price, was it acted on, and was it correct.
    """

    SIGNALS_FILE = SIGNALS_FILE

    def log_signal(self, signal: dict):
        """
        Append a signal record to the JSONL log.

        Required keys:
            id, timestamp, scan_time, ticker, action, score, conviction,
            price_at_signal, stop_loss, target, acted_on, skip_reason,
            analysis_summary, verified, price_1h_later, price_4h_later,
            price_eod, target_hit, stop_hit, signal_correct, accuracy_pct
        """
        SIGNALS_FILE.parent.mkdir(parents=True, exist_ok=True)

        # Ensure defaults for retroactive fields
        signal.setdefault("verified", False)
        signal.setdefault("price_1h_later", None)
        signal.setdefault("price_4h_later", None)
        signal.setdefault("price_eod", None)
        signal.setdefault("target_hit", None)
        signal.setdefault("stop_hit", None)
        signal.setdefault("signal_correct", None)
        signal.setdefault("accuracy_pct", None)

        with open(SIGNALS_FILE, "a") as f:
            f.write(json.dumps(signal) + "\n")

        logger.info(
            f"Signal logged: {signal.get('action')} {signal.get('ticker')} "
            f"@ {signal.get('price_at_signal')} | acted_on={signal.get('acted_on')}"
        )

    def _load_all(self) -> list:
        """Load all signal records from JSONL."""
        if not SIGNALS_FILE.exists():
            return []
        signals = []
        with open(SIGNALS_FILE) as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        signals.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        return signals

    def _save_all(self, signals: list):
        """Rewrite entire JSONL file with updated records."""
        SIGNALS_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(SIGNALS_FILE, "w") as f:
            for s in signals:
                f.write(json.dumps(s) + "\n")

    def get_unverified(self, older_than_hours: int = 4) -> list:
        """
        Returns signals not yet verified that are old enough to verify
        (i.e., timestamp is more than older_than_hours ago).
        """
        cutoff = datetime.now(timezone.utc) - timedelta(hours=older_than_hours)
        results = []
        for s in self._load_all():
            if s.get("verified"):
                continue
            try:
                ts = datetime.fromisoformat(s["timestamp"].replace("Z", "+00:00"))
                if ts < cutoff:
                    results.append(s)
            except Exception:
                pass
        return results

    def mark_verified(self, signal_id: str, verification: dict):
        """
        Update a signal record with verification data.

        verification = {
            "price_1h_later": float,
            "price_4h_later": float,
            "price_eod": float,
            "target_hit": bool,
            "stop_hit": bool,
            "signal_correct": bool,
            "accuracy_pct": float,
        }
        """
        signals = self._load_all()
        updated = False
        for s in signals:
            if s.get("id") == signal_id:
                s.update(verification)
                s["verified"] = True
                updated = True
                break

        if updated:
            self._save_all(signals)
            logger.info(f"Signal {signal_id} marked verified")
        else:
            logger.warning(f"Signal {signal_id} not found — cannot mark verified")

    def get_accuracy_stats(self, days: Optional[int] = None, ticker: Optional[str] = None,
                           scan_time: Optional[str] = None) -> dict:
        """
        Compute accuracy statistics across all verified signals.

        Filters:
            days      — only consider signals from last N days
            ticker    — only consider signals for this ticker
            scan_time — only consider signals from this scan window

        Returns:
        {
            "total_signals": int,
            "verified_signals": int,
            "buy_accuracy": float,
            "sell_accuracy": float,
            "pass_quality": float,
            "hold_accuracy": float,
            "by_scan_time": {"9:30": {"accuracy": 0.65, "count": 12}, ...},
            "by_ticker": {"NVDA": {"accuracy": 0.72, "count": 8}, ...},
            "best_scan_time": str,
            "worst_scan_time": str,
            "best_ticker": str,
            "worst_ticker": str,
        }
        """
        all_signals = self._load_all()

        # Apply filters
        if days:
            cutoff = datetime.now(timezone.utc) - timedelta(days=days)
            filtered = []
            for s in all_signals:
                try:
                    ts = datetime.fromisoformat(s["timestamp"].replace("Z", "+00:00"))
                    if ts >= cutoff:
                        filtered.append(s)
                except Exception:
                    pass
            all_signals = filtered

        if ticker:
            all_signals = [s for s in all_signals if s.get("ticker", "").upper() == ticker.upper()]

        if scan_time:
            all_signals = [s for s in all_signals if s.get("scan_time") == scan_time]

        verified = [s for s in all_signals if s.get("verified")]

        # Per-action accuracy
        def accuracy_for(action_filter):
            subset = [s for s in verified if s.get("action") == action_filter and s.get("signal_correct") is not None]
            if not subset:
                return 0.0
            return round(sum(1 for s in subset if s.get("signal_correct")) / len(subset), 4)

        # Pass quality: % of PASS signals where price DIDN'T go up (correct to skip)
        pass_quality = accuracy_for("PASS")

        # By scan time
        scan_time_map: dict = {}
        for s in verified:
            st = s.get("scan_time", "unknown")
            if st not in scan_time_map:
                scan_time_map[st] = {"correct": 0, "total": 0}
            if s.get("signal_correct") is not None:
                scan_time_map[st]["total"] += 1
                if s.get("signal_correct"):
                    scan_time_map[st]["correct"] += 1

        by_scan_time = {}
        for st, v in scan_time_map.items():
            acc = round(v["correct"] / v["total"], 4) if v["total"] > 0 else 0.0
            by_scan_time[st] = {"accuracy": acc, "count": v["total"]}

        # By ticker
        ticker_map: dict = {}
        for s in verified:
            t = s.get("ticker", "UNKNOWN")
            if t not in ticker_map:
                ticker_map[t] = {"correct": 0, "total": 0}
            if s.get("signal_correct") is not None:
                ticker_map[t]["total"] += 1
                if s.get("signal_correct"):
                    ticker_map[t]["correct"] += 1

        by_ticker = {}
        for t, v in ticker_map.items():
            acc = round(v["correct"] / v["total"], 4) if v["total"] > 0 else 0.0
            by_ticker[t] = {"accuracy": acc, "count": v["total"]}

        # Best / worst
        def _best(d):
            if not d:
                return None
            return max(d, key=lambda k: d[k]["accuracy"])

        def _worst(d):
            if not d:
                return None
            return min(d, key=lambda k: d[k]["accuracy"])

        return {
            "total_signals": len(all_signals),
            "verified_signals": len(verified),
            "buy_accuracy": accuracy_for("BUY"),
            "sell_accuracy": accuracy_for("SELL"),
            "pass_quality": pass_quality,
            "hold_accuracy": accuracy_for("HOLD"),
            "by_scan_time": by_scan_time,
            "by_ticker": by_ticker,
            "best_scan_time": _best(by_scan_time),
            "worst_scan_time": _worst(by_scan_time),
            "best_ticker": _best(by_ticker),
            "worst_ticker": _worst(by_ticker),
        }

    def get_signals(self, days: Optional[int] = None, ticker: Optional[str] = None,
                    scan_time: Optional[str] = None) -> list:
        """Return filtered list of all signals (verified and unverified)."""
        all_signals = self._load_all()

        if days:
            cutoff = datetime.now(timezone.utc) - timedelta(days=days)
            filtered = []
            for s in all_signals:
                try:
                    ts = datetime.fromisoformat(s["timestamp"].replace("Z", "+00:00"))
                    if ts >= cutoff:
                        filtered.append(s)
                except Exception:
                    pass
            all_signals = filtered

        if ticker:
            all_signals = [s for s in all_signals if s.get("ticker", "").upper() == ticker.upper()]

        if scan_time:
            all_signals = [s for s in all_signals if s.get("scan_time") == scan_time]

        return all_signals
